### ISSUE TITLE
Take latest commit when querying for a branch

### ISSUE THREAD

**Issue by dword-design** [EqualMa/gitpkg#17]
Currently, when querying via e.g. ?fork, the first commit of that branch (or at least not the lastest) is taken when adding a repo to the package. I think it makes more sense to always take the latest one.

**Comment by EqualMa** [comment]
Can you give an example? 
I think the current behavior is taking the latest commit rather than the first.

**Comment by dword-design** [comment]
Never mind, it was the good ol' Yarn cache. There is an open issue about caching git dependencies.
