### ISSUE TITLE
502 Bad gateway

### ISSUE THREAD

**Issue by kigawas** [EqualMa/gitpkg#20]
With this url:
https://gitpkg.now.sh/kigawas/openzeppelin-sdk/packages/cli?http-solc

**Comment by kigawas** [comment]
![image](https://user-images.githubusercontent.com/4182346/94103905-a66a5480-fe70-11ea-9892-91354a28859d.png)

**Comment by EqualMa** [comment]
This error happens because the file size exceed the Lambda limit (`soljson-vx.x.x+commit.e67f0147.js` are too large)

You can see more info in this issue: #16
