### ISSUE TITLE
How to write a custom script to download a subfolder without a package.json?

### ISSUE THREAD

**Issue by tommy-mitchell** [EqualMa/gitpkg#33]
I'm trying to download a subfolder of a repo that's purely source code. The documentation on custom scripts say that

`Many github repositories contains source code only, which you can't use directly as a npm/yarn dependency. So this service provide the option to configure custom scripts.`

There's no further explanation on how that works, though. What should the script contain?

**Comment by EqualMa** [comment]
Custom scripts only works when there is a `package.json` and this subfolder is installed with npm, yarn or other tools that respects `package.json` scripts. When the subfolder is intalled, the `postinstall` script in `package.json` will be runned by npm and yarn ( not GitPkg service ). Thus custom scripts doesn't support subfolders without `package.json`. Sorry for that. But you can fork the original repo and add a `package.json` into that folder.

**Comment by tommy-mitchell** [comment]
I ended up just adding the entire repo as a dependency and using a script to make a couple of changes as I needed. Thanks for the help.
