### ISSUE TITLE
Unexpected end of file

### ISSUE THREAD

**Issue by Jade-GG** [EqualMa/gitpkg#48]
I'm trying to use gitpkg to install a patch in ReactiveSearch with the following url:

`https://gitpkg.vercel.app/api/pkg?url=Jade-GG/reactivesearch/packages/vue&commit=patch-4&scripts.postinstall=yarn%20install%20--ignore-scripts%20%26%26%20yarn%20run%20build-es&scripts.build-es=nps%20build.es`

However, I get this output from yarn add: `error An unexpected error occurred: "[...]: unexpected end of file".`

Given that the runtime of this download is suspiciously close to 30 seconds, my guess was that I needed to increase the yarn network timeout delay. This, however, didn't make a difference.

If I download the file manually, it outputs an incomplete tgz file:

```
[...]
x package/src/components/search/
x package/src/components/search/DataSearch.jsx: truncated gzip input
tar: Error exit delayed from previous errors.
```

Is the server maybe timing out the request and just spitting out what it's sent so far?

**Comment by EqualMa** [comment]
This should be fixed by #49. Please retry this url.
