### ISSUE TITLE
gitpkg.now.sh completely down

### ISSUE THREAD

**Issue by thecodeassassin** [EqualMa/gitpkg#58]
gitpkg.now.sh does not resolve anymore, this breaks a couple packages for us.

**Comment by jLynx** [comment]
Same here

**Comment by thecodeassassin** [comment]
We changed all uses of gitpkg.com with:

```
user/repo#commit-or-tag-or-branch:path/to/subdirectory
```

**Comment by jLynx** [comment]
You mean with ``https://github.com/user/repo#commit-or-tag-or-branch:path/to/subdirectory`` ?

**Comment by snowystinger** [comment]
Down for us as well
and unfortunately I can't quite seem to get `https://github.com/user/repo#commit-or-tag-or-branch:path/to/subdirectory` to work, it keeps giving me
`Couldn't find match for "branch:path/to/subdirectory" in "refs/heads/branch" for "https://github.com/user/repo".`

Edit: looks like we have to be on something newer than yarn 1.x... sigh

Edit Edit: ! the service was renamed, you can use `gitpkg.vercel.app`

**Comment by jLynx** [comment]
Thanks @snowystinger, replacing the domain with gitpkg.vercel.app worked

**Comment by thecodeassassin** [comment]
Oh man why was this done?!  I figure that someone wanted to migrate it to a free domain and let the old domain expire? But why do that? I'd happily pay the domain renewal fee if I knew this was happening. This issue has caused us hours of additional work.

Btw in your how-to section you are still referencing gitpkg.now.sh.

**Comment by EqualMa** [comment]
Sorry about this, I will update the docs. Please replace the domain with `gitpkg.vercel.app`.

gitpkg is deployed on a free platform Vercel. They migrated from *.now.sh to *.vercel.app years ago. *.now.sh used to correctly redirect to the new domain so the docs of gitpkg were not updated.

**Comment by d07RiV** [comment]
Front page still provides old links in Yarn/NPM commands

**Comment by EqualMa** [comment]
The docs are updated in 7f90734b34644792ced5c04ae567cfe8c6649d0f
