### ISSUE TITLE
feature request: custom install/prepare script

### ISSUE THREAD

**Issue by EqualMa** [EqualMa/gitpkg#6]
Custom install/prepare script allows user to do something after the package is installed such as building from ts source.

It should respect the original install/prepare script.

**Comment by ulion** [comment]
+1
Great service, just the same little problem here.
The original git include only source, not built lib files, then after npm install / yarn add I only got source files, no lib. it seems I can only build it locally and add lib files to repo too for now, that's not sweet. any suggestion?

**Comment by EqualMa** [comment]
Currently https://gitpkg.now.sh supports custom scripts, which means you can add custom scripts to the repo's `package.json` where build steps can be done. (But the docs are not updated and I am working on it at branch `docs/custom-scripts`).

## For example:

```
mkdir hello-gitpkg
cd hello-gitpkg
npm init -y
npm install 'https://gitpkg.now.sh/EqualMa/gitpkg-hello/packages/hello-ts?master&scripts.postinstall=npm%20install%20--ignore-scripts%20%26%26%20npm%20run%20build'
```

Then make a file `test.js`

```js
const { hello } = require("hello-ts");
console.log(hello("world"));
```

run `node test.js`. Outputs: `Hello world from TypeScript!`

## How it works

the query param `scripts.postinstall=npm install --ignore-scripts && npm run build` will tell GitPkg to add an custom script `postinstall` to the dependency's `package.json`, which build the source code to js.

> Note that running `npm install '...'` or `yarn add '...'` when the arg contains `&` may not works in WIndows. In such cases, you have to add to add the following to your `package.json` manually and running `npm install` or `yarn install` to install the dependencies.
>
> ```json
>   "dependencies": {
>     "hello-ts": "https://gitpkg.now.sh/EqualMa/gitpkg-hello/packages/hello-ts?master&scripts.postinstall=npm%20install%20--ignore-scripts%20%26%26%20npm%20run%20build"
>   }
> ```

**Comment by EqualMa** [comment]
Now this feature is implemented and well documented. Just try adding custom scripts at https://gitpkg.now.sh
